// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Har.Infrastructure.Data.Kontent.Types
{
    public partial class ImageSlider
    {
        public const string Codename = "image_slider";
        public const string ImagesCodename = "images";

        public IEnumerable<IAsset> Images { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}